spring.application.name=ServiceInventario
server.port=8181
server.servlet.context-path=/api

#DB
spring.datasource.url=jdbc:postgresql://localhost:5432/inventario
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=admin
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

file.upload-dir = ./uploads/

# Tamaño máximo de archivo
spring.servlet.multipart.max-file-size=50MB
# Tamaño máximo de la solicitud (archivo + otros datos)
spring.servlet.multipart.max-request-size=50MB